(ns flo-invest.core-test
  
  (:require [clojure.data :refer :all]
            [clojure.test :refer :all]
            [flo-invest.core :refer :all]
            [clojure.java.io :as io]
            [cheshire.core :refer :all]
            [cheshire.factory :as factory])
  (:import [org.joda.money BigMoney])
            )




(deftest test-data-available
  (let  [testdata (parse-dir "/home/flo/geldanlage/aktienscreen_2013_10_05/data/morningstar/2013_10_05/")]
    (testing "loading test data succeeds"
      (is (not= testdata []))
      (is (= 3 (count  (first (vals testdata)))))
      )))

(deftest test-loading-of-hfc-stock
  (let [testdata "/home/flo/geldanlage/aktienscreen_2013_10_05/data/morningstar/2013_10_05/"
        input (load-data [{:isin "US4361061082" :type :balancesheet :file (io/file (str testdata  "US4361061082 Balance Sheet.csv")) }
                     {:isin "US4361061082" :type :incomestatement :file (io/file (str testdata  "US4361061082 Income Statement.csv"))}
                     {:isin "US4361061082" :type :keyratios :file (io/file (str testdata  "US4361061082 Key Ratios.csv"))}])

        expected {:isin "US4361061082",
                    :annual_sales 20091e6,
                    :currency "USD",
                    :current_assets 4470e6,
                    :current_liabilities 1654e6,
                    :dividends [0.06, 0.07, 0.1, 0.15, 0.23, 0.3, 0.3, 0.3, 0.34, 0.6],
                    :eps [0.36, 0.65, 1.33, 2.29, 2.99, 1.19, 0.2, 0.97, 6.42, 8.38],
                    :goodwill 2338e6,
                    :intangibles 169e6,
                    :long_term_debt 1336e6,
                    :non_redeemable_preferred_stock 0.0e6,
                    :redeemable_preferred_stock 0.0e6,
                    :reported_book_value 29.74,
                    :shares_outstanding 206e6,
                    :split_bonus_factor 1.0,
                    :tangible_book_value 17.57009708737864,
                    :total_assets 10329.0e6,
                    :total_liabilities 4276e6}]
    (testing "Result from calling load-data is as expected"
      (is (= (diff input expected)  [nil nil expected]))
      )))

(deftest  test-data-loads-without-hickups
  (testing "test that all data files can be loaded"
    (doseq [testdata (parse-dir "/home/flo/geldanlage/aktienscreen_2013_10_05/data/morningstar/2013_10_05/")]
      (is (not= {} (load-data (last  testdata))) (first testdata)))))

(deftest test-as-float
  (is (= (as-float "1.23") 1.23))
  (is (= (as-float "1,234.56") 1234.56))
  (is (Double/isNaN (as-float ""))))

(deftest test-as-money
  (is (= (as-money "1.23" "EUR") (BigMoney/parse "EUR 1.23")))
  (is (= (as-money "1,234.56" "EUR") (BigMoney/parse "EUR 1234.56")))
  (is (= (as-money "0.11" "CNY") (BigMoney/parse "CNY 0.11")))
  (is (= (as-money "" "EUR") nil)))

(deftest money-and-nans
  (testing "My own numeric tower that handles nil and NaN as missing values"
    (doseq [func [plus minus multiply divide]]
      (is (= (func (BigMoney/parse "EUR 1.23") nil) nil) (str "function: " func))
      (is (= (func (BigMoney/parse "EUR 1.23") Double/NaN) nil)(str "function: " func))
      (is (= (func nil (BigMoney/parse "EUR 1.23")) nil)(str "function: " func))
      (is (= (func Double/NaN (BigMoney/parse "EUR 1.23")) nil))(str "function: " func)
      )))

(defn eq
  "Equality helper to test equality of data generated by Cheshire that
  includes NaNs."
  [a b]
  (cond
   (and (vector? a) (vector? b)) (cons (= (count a) (count b)) (map eq a b))
   (and (number? a) (number? b) (Double/isNaN a) (Double/isNaN b)) true
   (and (number? a) (number? b)) (== a b)
   :else (= a b)))

(deftest  compare-with-python-results
  (let [py-data (binding [factory/*json-factory*
                           (factory/make-json-factory {:allow-non-numeric-numbers true})]
                   (parse-stream (clojure.java.io/reader
                                  "/home/flo/geldanlage/aktienscreen_2013_10_05/morningstar.json")))
        clj-data (vec (for [input (parse-dir "/home/flo/geldanlage/aktienscreen_2013_10_05/data/morningstar/2013_10_05/" )] (load-data (last input))))
        py-keys [:isin :currency :annual_sales :current_assets :current_liabilities
                 :dividends :eps :goodwill :intangibles :long_term_debt
                 :non_redeemable_preferred_stock :redeemable_preferred_stock
                 :reported_book_value :shares_outstanding :split_bonus_factor
                 :tangible_book_value :total_assets :total_liabilities]]
    (doseq [[py clj] (map list  (sort-by :isin (map #(zipmap py-keys %) py-data)) (sort-by :isin clj-data))
            key py-keys]
      (is (eq (py key) (clj key)) (str (py :isin) key)))
    ))
